/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.iss.ects.strust.action;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import edu.iss.ects.entity.Comment;
import edu.iss.ects.entity.Product;
import edu.iss.ects.entity.ShopCart;
import edu.iss.ects.entity.User;
import edu.iss.ects.imp.CommentDAO;
import edu.iss.ects.imp.ProductDAO;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CommentAction extends DispatchAction {
	
	
	public ActionForward checkOrder(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String url = "";
		
		//判断用户是否登录
		HttpSession session = request.getSession();
		User user  = (User)session.getAttribute("user");
		if(user == null)
		{
			//没有登录，跳转到登陆页面登录后回到购物车
			url = "toLogin";
		}else
		{
			url = "toAdd";
		}
		
		return mapping.findForward(url);
	} 
    
	
	
	
	
	public ActionForward addComment(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		HttpSession session = request.getSession();
		Product product = (Product)session.getAttribute("details");
		int prodId = product.getProductId();
		System.out.println(prodId);
		String description = request.getParameter("comment");
	
		User user  = (User)session.getAttribute("user");
		int userId = user.getUserId();
		System.out.println(userId);
		
		
		Comment c = new Comment();
		c.setUser(user);
		c.setProduct(product);
		c.setDescription(description);
		c.setScore(10);
		CommentDAO cd = new CommentDAO();
		cd.save(c);
		
		
		return mapping.findForward("toDetails");
		
	}
	
	
	public ActionForward findById(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String pid = request.getParameter("prodId");
		int prodId  = Integer.parseInt(pid);
		
		
		
		List list = new ArrayList();
		CommentDAO cd = new CommentDAO();
		list = cd.findByProductId(prodId);
		Iterator it = list.iterator();
		while (it.hasNext()) {
			Comment c = (Comment) it.next();
			System.out.println( c.getDescription());
		}
		HttpSession session = request.getSession();
		session.setAttribute("comdes", list);
		

		return mapping.findForward("toDetails");
	}
	
	
	
	
	
}