/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.iss.ects.strust.action;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import edu.iss.ects.entity.Orderline;
import edu.iss.ects.entity.Orders;
import edu.iss.ects.entity.Orderstatus;
import edu.iss.ects.entity.Payway;
import edu.iss.ects.entity.ShopCart;
import edu.iss.ects.entity.User;
import edu.iss.ects.imp.OrdersDAO;



/** 
 * 专门处理与订单有关的请求
 */
public class OrderAction extends DispatchAction {

	public ActionForward checkOrder(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String url = "";
		
		//判断用户是否登录
		HttpSession session = request.getSession();
		User user  = (User)session.getAttribute("user");
		if(user == null)
		{
			//没有登录，跳转到登陆页面登录后回到购物车
			url = "toLogin";
		}else
		{
			url = "toOrderShow";
		}
		
		return mapping.findForward(url);
	}
	
	
	
	public ActionForward orderShow(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//得到订单确认页面所需要的数据，购物车中所有数据和用户所有数据
		HttpSession session = request.getSession();
		ShopCart cart = (ShopCart) session.getAttribute("cart");

		// 从购物车中，取出产品明细列表
		Collection list = cart.getOrder().getOrderlines();
		// 从购物车中，取出商品总个数
		int count = cart.getCount();
		// 从购物车中，取出商品总价格
		double total = cart.getTotal();

		// 把上述三个数据传递给 购物车页面显示
		request.setAttribute("list", list);
		request.setAttribute("count", count);
		request.setAttribute("total", total);
		
		
		return mapping.findForward("toOrder");
	}
	
	
	public ActionForward saveOrder(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{
			//得到用户信息
			HttpSession session = request.getSession();
			User  user  = (User) session.getAttribute("user");
            
			//从页面得到付款方式
			Integer  pay_id = new Integer(request.getParameter("payway"));
			Payway  pay = new Payway();
			pay.setPaywayId(pay_id);
		
			String a =pay.getPaystyle();
			System.out.println(a);
			Orderstatus  status = new Orderstatus();
			status.setOrderstatusId(new Integer(1));
			String b =status.getName();
			System.out.println(b);
			//从 session 中取出购物车对象
			ShopCart  cart = (ShopCart) session.getAttribute("cart");
			Orders  order = cart.getOrder();
			Iterator it = cart.getItems().values().iterator();
			while(it.hasNext()){
				Orderline line = (Orderline) it.next();
				line.setOrder(order);
			}
			
			order.setCost(cart.getTotal());
			order.setPayway(pay);
			order.setOrderstatus(status );
			order.setUser(user);
	
			
			session.setAttribute( "order", order);
			request.setAttribute("count", new Integer(cart.getCount()));
			request.setAttribute("total", new Double(cart.getTotal()));
			
			//把订单数据插入数据库
			OrdersDAO odao = new OrdersDAO();
			odao.save(order);
			List list = odao.findByUserId(user.getUserId());
			session.setAttribute("list", list);
			System.out.println(order.getOrderstatus().getName());
			System.out.println(order.getPayway().getPaystyle());
			
			session.setAttribute("cart", null);
		}catch(Exception e){
			
		}
		//跳转到订单列表页面
		return  mapping.findForward("tolist");
	}
	
	
	

}