/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.iss.ects.strust.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import edu.iss.ects.entity.User;
import edu.iss.ects.strust.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		System.out.println("userForm..................");
		//得到页面输入的数据
		UserForm user = (UserForm)form;
		
		//验证输入
	
		System.out.println("city ="+user.getInfo().getCity());
		System.out.println("Steet1 ="+user.getInfo().getStreet1());

		System.out.println("email ="+user.getInfo().getEmail());
		

		return null;
	}
}